version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"
    allow:
      # Allow only patch and minor updates
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "npm"
      - "dependencies"
    assignees:
      - "phazonoverload"
  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Group GitHub Actions updates by type
    groups:
      actions-testing:
        patterns:
          - "jest*"
          - "mocha*"
          - "*test*"
      actions-deployment:
        patterns:
          - "deploy*"
          - "*aws*"
